@extends('layouts.company')
@section('title', 'Application Details - OnlyFreshers')
@section('pageTitle', 'Application Details')
@section('pageSubtitle', 'Review candidate application details.')
@php $activePage = 'applications'; @endphp
@section('content')
<section class="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><div class="rounded-lg border border-[#dce7f8] bg-white p-6 shadow-[0_10px_24px_rgba(6,25,66,0.04)]"><div class="mb-6 flex items-center gap-4"><div class="flex h-20 w-20 items-center justify-center rounded-full bg-[#eaf2ff] text-xl font-bold text-[#075fe4]">RK</div><div><h2 class="text-xl font-bold text-[#061942]">Rohit Kumar</h2><p class="text-sm text-[#52607a]">rohit.kumar@email.com</p></div></div><div class="grid gap-4 md:grid-cols-2"><div><b class="text-sm">Applied For</b><p class="mt-1 text-sm text-[#24344f]">Full Stack Developer</p></div><div><b class="text-sm">Experience</b><p class="mt-1 text-sm text-[#24344f]">0 - 1 Year</p></div><div><b class="text-sm">Applied Date</b><p class="mt-1 text-sm text-[#24344f]">02 Jun 2024</p></div><div><b class="text-sm">Status</b><p class="mt-1 inline-flex rounded-lg bg-[#eaf2ff] px-3 py-1 text-xs font-bold text-[#075fe4]">New</p></div></div><h3 class="mb-2 mt-6 font-bold">Cover Note</h3><p class="text-sm leading-relaxed text-[#24344f]">I am excited to apply for this role and bring strong full-stack fundamentals to your engineering team.</p></div><aside class="rounded-lg border border-[#dce7f8] bg-white p-5 shadow-[0_10px_24px_rgba(6,25,66,0.04)]"><h3 class="mb-4 font-bold">Actions</h3><div class="grid gap-3"><a href="/company/shortlisted" class="inline-flex h-10 items-center justify-center rounded-lg bg-[#075fe4] text-sm font-bold text-white">Shortlist</a><a href="/company/interviews/create" class="inline-flex h-10 items-center justify-center rounded-lg border border-[#9fc0f5] text-sm font-bold text-[#075fe4]">Schedule Interview</a><a href="/company/applications" class="inline-flex h-10 items-center justify-center rounded-lg border border-[#ffd1d7] text-sm font-bold text-[#ff3045]">Reject</a></div></aside></section>
@endsection

